.TH "ANI-CLI" "1" "Ocak 2023" "ani-cli" "Kullanıcı Komutları"
.SH NAME
ani-cli \- komut satırından anime izleyin
.SH SYNOPSIS
.B ani-cli
[\fI\, SEÇENEKLER\/\fR]
.SH DESCRIPTION
Komut satırından anime taramak ve aramak için bir shell script.
.PD 0
.P
.PD
Bu araç allanime sitesini kazır.
.PD 0
.P
.PD
\f[B]ani-cli\f[R] seçenekler olmadan varsayılan olarak macOS'ta iina, Steamdeck'te flatpak mpv, android'de mpv apk ve diğer her yerde mpv medya oynatıcıyı kullanmaktadır.
.SH OPTIONS
.TP
\fB\-e | --bölüm | -r | --aralık\fR \fI\,<bölüm>\/\fR
İzlenecek bölüm numaralarını belirtin. Aralık belirtilirse, tırnak içine alınmalı veya sayısal olmayan bir karakterle (örn. -) ayrılmalıdır.
.TP
\fB\-c | -continue\fR
Kaldığınız yerden anime izlemeye devam edin.
.TP
\fB\-d | --download\fR
Bölümü indir.
.TP
\fB\-D | --delete\fR
Geçmişi sil.
.TP
\fB\-S | --select-nth\fR \fI\,<index>\/\fR
N'inci girişi seçer.
.TP
\fB\-h | --help\fR
Seçeneklerin özetini gösterir.
.TP
\fB\-q | --kalite\fR \fI\,<best|worst|360|480|720|1080>\/\fR
Video kalitesini ayarlayın. Varsayılan kalite (best) en iyisidir.
.TP
\fB\-s | --syncplay\fR
Syncplay kullanarak arkadaşlarınızla birlikte anime izleyin (yalnızca mpv ile çalışır).
.TP
\fB\-U | --update\fR
Github'dan güncelleme indir.
.TP
\fB\-v | --vlc\fR
Medya oynatıcı olarak VLC kullanın.
.TP
\fB\-V | --version\fR
Sürüm numarasını yazdırın ve çıkın.
.TP
\fB\--dub\fR
Dublajlı versiyonu oynat. Bu bayrak olmadan, her zaman altyazılı sürümü oynatır.
.PP
.SH
ENVIRONMENT VARIABLES
.PP
ani-cli v4, seçeneği olan her şeye ek olarak kararsız/test edilmemiş ve niş özellikleri kontrol etmek için ortam değişkenlerini kullanır. Komut satırı seçenekleri env değişkenlerine göre önceliklidir. Bunların hepsinin değişime tabi olduğunu unutmayın.
.TP
\fBANI_CLI_MODE\fR
Kazınan medyanın modunu kontrol eder, geçerli seçenekler sub veya dub'dır. Varsayılan sub'dır.
.TP
\fBANI_CLI_DOWNLOAD_DIR\fR
Dosyaların indirileceği dizini kontrol eder. Varsayılan geçerli dizindir.
.TP
\fBANI_CLI_QUALITY\fR
Kazınan medyanın kalitesini kontrol eder, geçerli seçenekler için allanime'yi kontrol edin veya en kötü/en iyi olarak ayarlayın. Varsayılan en iyisidir.
.TP
\fBANI_CLI_PLAYER\fR
ani-cli'nin kullandığı oynatıcıyı ayarlar. Debug (bağlantıları yazdır), download (-d'ye eşdeğer), android_mpv (apk ve am start), android_vlc (apk ve am start), flatpak_mpv (flatpak için), catt (tv'ye akış için) veya URL'leri oynatabilen herhangi bir oynatıcı olabilir. Varsayılanlar için argümansız çalışma bölümüne bakınız.
.TP
\fBANI_CLI_EXTERNAL_MENU\fR
ani-cli'nin önyüzünü kontrol eder. 0 (fzf kullanır) veya 1 (rofi dmenu kullanır) olabilir. Varsayılan değer 0'dır.
.TP
\fBANI_CLI_MULTI_SELECTION\fR
Seçilen ön uç için çoklu bayrağı kontrol eder. Varsayılan değer fzf için -m ve rofi dmenu için --multi-select'tir.
.TP
\fBANI_CLI_CACHE_DIR\fR
ani-cli'nin sonuçları önbelleğe almak için kullandığı dizini kontrol eder. Eğer yoksa önbellek dosyaları için bir /ani-cli alt klasörü oluşturulur. Varsayılan, ayarlanmışsa $XDG_CACHE_HOME, ayarlanmamışsa $HOME/.cache/'dir.
.TP
\fBANI_CLI_HIST_DIR\fR
ani-cli'nin geçmişi depolamak için kullandığı dizini kontrol eder. Eğer mevcut değilse hist dosyası için bir /ani-cli alt klasörü oluşturulur. Varsayılan, ayarlanmışsa $XDG_STATE_HOME, ayarlanmamışsa $HOME/.local/state'dir.
.TP
\fBANI_CLI_DEFAULT_SOURCE\fR
Varsayılan kaynağı kontrol eder. Geçerli olan geçmiş (-c ile eşdeğerdir), diğer her şey arama anlamına gelir. Varsayılan kaynak aramadır.
.PP
.SH EPISODE SELECTION
.PP
Birden fazla bölüm fzf (veya alternatif ön uç) çoklu seçim modu kullanılarak seçilebilir. Bunun için talimatlarına bakın.
.SH BUGS
.PP
GitHub sorun izleyicisini kullanın:
https://github.com/pystardust/ani-cli/issues
.SH COPYRIGHT
.PP
ani-cli, GNU Genel Kamu Lisansı v3.0 altında lisanslanmıştır
.PP
Bu program özgür yazılımdır: Özgür Yazılım Vakfı tarafından yayınlanan 
GNU Genel Kamu Lisansı koşulları altında, Lisansın 3. sürümü veya 
(sizin tercihinize bağlı olarak) daha sonraki herhangi bir sürümü 
altında yeniden dağıtabilir ve/veya değiştirebilirsiniz.
.PP
Bu program, yararlı olacağı umuduyla, ancak HERHANGİ 
BİR GARANTİ OLMAKSIZIN; hatta ZIMNİ TİCARİ ELVERİŞLİLİK veya 
BELİRLİ BİR AMACA UYGUNLUK garantisi olmaksızın dağıtılmaktadır. 
Daha fazla ayrıntı için GNU Genel Kamu Lisansına bakınız.
.PP
Bu programla birlikte GNU Genel Kamu Lisansının bir kopyasını almış olmalısınız. 
Almadıysanız , <http://www.gnu.org/licenses/> adresine bakın.
